apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-microservice
  name: go-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-microservice
  strategy: {}
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
      - image: polinchw/go-microservice:0.1.1
        name: go-microservice
        resources: 
          limits:
            cpu: 150m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 50Mi
